# Generated by Django 5.0.4 on 2024-06-12 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(upload_to='static/Logo')),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_title', models.CharField(max_length=1000)),
                ('conference_description', models.TextField()),
                ('conference_logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conference.logomodel')),
            ],
        ),
    ]
