# Generated by Django 5.0.4 on 2024-06-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conferencemodel',
            table='conferences',
        ),
        migrations.AlterModelTable(
            name='logomodel',
            table='logo',
        ),
    ]
